/**
 * Tenant rights in New York City — fixed reference text.
 *
 * Every entry is transcribed from HPD's own "Tenants' Rights and
 * Responsibilities" page, read 2026-09-27, and carries a link back to it.
 * Nothing here is generated by a model and nothing here is inferred: wrong
 * housing law is worse than no housing law, and a tenant may act on it.
 *
 * This is the general guide. `lib/rights.ts` is the other half — the rights
 * picked out for one specific building by what its record actually shows.
 *
 * Deliberately NOT stated anywhere below: how long a landlord has to correct a
 * violation. HPD sets that per violation on the Notice of Violation; there is
 * no single deadline per class, and inventing one would be the most damaging
 * kind of error this file could make.
 */

export const HPD_TENANT_RIGHTS_URL =
  'https://www.nyc.gov/site/hpd/services-and-information/tenants-rights-and-responsibilities.page';

const HPD_HEAT_URL =
  'https://www.nyc.gov/site/hpd/services-and-information/heat-and-hot-water-information.page';
const HPD_ABCS_URL = 'https://www.nyc.gov/site/hpd/services-and-information/abcs-of-housing.page';
const HPD_GOOD_CAUSE_URL =
  'https://www.nyc.gov/site/hpd/services-and-information/good-cause-eviction.page';
const NYC311_URL = 'https://portal.311.nyc.gov/';
const HOUSING_COURT_URL = 'https://www.nycourts.gov/courts/nyc/housing/';
const DHCR_URL = 'https://hcr.ny.gov/';
const FAIR_HOUSING_URL = 'https://www.nyc.gov/site/fairhousing/index.page';
const CCHR_URL = 'https://www.nyc.gov/site/cchr/index.page';

export interface RightsSource {
  readonly label: string;
  readonly url: string;
}

export interface RightsTopic {
  readonly id: string;
  readonly title: string;
  /** One line a tenant can act on, before any detail. */
  readonly headline: string;
  readonly detail: readonly string[];
  /** Statute citation, where HPD gives one. */
  readonly statute?: string;
  readonly sources: readonly RightsSource[];
}

export interface RightsGroup {
  readonly id: string;
  readonly title: string;
  readonly blurb: string;
  readonly topics: readonly RightsTopic[];
}

const HPD: RightsSource = { label: 'NYC HPD', url: HPD_TENANT_RIGHTS_URL };
const CALL_311: RightsSource = { label: 'File with 311', url: NYC311_URL };

export const RIGHTS_GROUPS: readonly RightsGroup[] = [
  {
    id: 'conditions',
    title: 'When something is broken',
    blurb: 'Conditions the owner has to fix, and what to do when they do not.',
    topics: [
      {
        id: 'heat',
        title: 'Heat and hot water',
        headline: 'Hot water all year. Heat from 1 October to 31 May.',
        detail: [
          'Between 6am and 10pm, when it is below 55°F outside, the owner must heat your apartment to at least 68°F. HPD can only issue a violation for inadequate heat when it is below 55°F outside.',
          'Between 10pm and 6am the apartment must be at least 62°F, whatever the temperature outside.',
          'Hot water must run at a minimum of 120°F, 24 hours a day, every day of the year — not only in heat season.',
          'No heat or hot water is a 311 complaint. Make it while the condition is happening.',
        ],
        sources: [HPD, { label: 'HPD heat and hot water', url: HPD_HEAT_URL }, CALL_311],
      },
      {
        id: 'repairs',
        title: 'Repairs the owner will not make',
        headline: 'Build a paper trail, then use it. You do not need a lawyer.',
        detail: [
          'Ask the owner, managing agent or superintendent first.',
          'If nothing happens, write a letter describing the problems and setting a date. Send it by certified mail and keep a copy. Owners must file their contact details with HPD every year, so you can look the address up if you do not have it.',
          'Then try in person or by phone, and keep a record of every attempt — it is useful in court.',
          'If there is still no response, file a complaint with HPD, and you can bring an HP Action in Housing Court to get an order forcing the repairs. You start one at the Clerk’s Office, and you do not need a lawyer to do it.',
          'In a rent controlled or rent stabilized apartment you can also complain to the State (DHCR, 718-739-6400), which can cut your rent if the complaint holds up.',
        ],
        sources: [
          HPD,
          CALL_311,
          { label: 'Housing Court', url: HOUSING_COURT_URL },
          { label: 'NYS DHCR', url: DHCR_URL },
        ],
      },
      {
        id: 'paint',
        title: 'Painting',
        headline: 'Every three years, in any building with three or more apartments.',
        detail: [
          'In a multiple dwelling the owner must paint occupied apartments every three years. In smaller private dwellings they must be painted as necessary.',
          'Report peeling paint to the owner. If it is not fixed, or if work is being done in a way that spreads dust, call 311 — particularly if a child under six lives there.',
        ],
        statute: 'NYC Administrative Code §27-2013',
        sources: [HPD, CALL_311],
      },
      {
        id: 'window-guards',
        title: 'Window guards',
        headline: 'Ask in writing and the owner must install them. No children required.',
        detail: [
          'Any tenant can request window guards in writing for any reason, even with no resident child aged ten or under — grandchildren who visit, shared custody, childminding all count.',
          'Call 311 if guards are not installed after being required or requested, look insecure or badly fitted, or leave more than four and a half inches of open unguarded space.',
        ],
        sources: [HPD, CALL_311],
      },
    ],
  },
  {
    id: 'home',
    title: 'Your home is yours',
    blurb: 'Who may come in, and what an owner may never do.',
    topics: [
      {
        id: 'entry',
        title: 'Can the landlord come in?',
        headline: 'In an emergency, yes, at any time. Otherwise only with notice.',
        detail: [
          'Generally no. In an emergency the owner may enter at any time without notice.',
          'Otherwise they may enter at a reasonable time after appropriate notice, to make necessary or agreed repairs and services, in accordance with the lease, or to show the apartment to prospective tenants or purchasers.',
        ],
        sources: [HPD],
      },
      {
        id: 'lockout',
        title: 'Lockouts',
        headline: 'Changing your locks without giving you a key is illegal.',
        detail: [
          'Without a warrant of eviction it violates the Unlawful Eviction Law. It applies to a tenant or subtenant with a lease, anyone who has lawfully lived there more than thirty days with or without a lease, and a subtenant, roommate or relative who has lived there at least thirty days even if they are not on the lease and have never paid the landlord directly.',
          'Report it at the nearest police station, and you can start an illegal lockout case in Housing Court.',
          'Keep proof you live there — lease, rent receipts, utility bills, mail, ID — and leave copies with someone outside the apartment in case you cannot get back in.',
          'If you change your own locks, the law requires you to give the owner a copy of the key.',
        ],
        statute: 'NYC Administrative Code §26-521 · RPAPL §853',
        sources: [HPD, { label: 'Housing Court', url: HOUSING_COURT_URL }],
      },
      {
        id: 'harassment',
        title: 'Harassment',
        headline: 'Pressuring you out of your apartment is against the law.',
        detail: [
          'Owners are prohibited from harassing tenants to force them out. Verbal or physical abuse, consistently withholding services, and persistent physical or mental intimidation are all examples.',
          'Any tenant in a building with three or more units — rent regulated or not — who believes they are being harassed may have grounds to start an action in Housing Court. Free or low-cost legal help may be available.',
        ],
        sources: [HPD, { label: 'Fair Housing NYC', url: FAIR_HOUSING_URL }],
      },
      {
        id: 'immigration',
        title: 'Immigration status',
        headline: 'Your rights as a tenant do not depend on your documents.',
        detail: [
          'Immigrant New Yorkers have the same rights and responsibilities in housing as every other tenant, regardless of documentation status.',
          'An owner may not treat you differently because of immigration or citizenship status or national origin — including by refusing repairs, or by renting on different terms.',
          'Threatening to call ICE, retaliating because you complained or organised, or otherwise intimidating you over your status is illegal and counts as harassment.',
          'Report discrimination to the NYC Commission on Human Rights at (212) 416-0127.',
        ],
        sources: [HPD, { label: 'NYC Commission on Human Rights', url: CCHR_URL }],
      },
    ],
  },
  {
    id: 'money',
    title: 'Rent and deposits',
    blurb: 'What can go up, by how much, and what has to come back.',
    topics: [
      {
        id: 'increase',
        title: 'Rent increases',
        headline: 'If the apartment is regulated, the increase is capped by the city.',
        detail: [
          'In a rent controlled or rent stabilized apartment, DHCR and the Rent Guidelines Board set how much the owner may raise the rent. DHCR can tell you whether an increase is too high.',
          'If you do not know whether your apartment is regulated, call DHCR on 718-739-6400 or request your apartment’s rental history — the history is the document that settles it.',
          'If the apartment is not regulated and you have a lease, the legal rent is what the lease says and can only rise as the lease permits or when it expires. With no lease, the owner may raise it to any amount provided they tell you a month beforehand.',
          'In public or subsidised housing, increases follow that programme’s rules and are usually tied to household income.',
        ],
        sources: [HPD, { label: 'NYS DHCR', url: DHCR_URL }],
      },
      {
        id: 'deposit',
        title: 'Security deposit',
        headline: 'You get it back, with interest, and they have fourteen days.',
        detail: [
          'At the end of the tenancy you are entitled to your deposit back with interest. The owner may inspect for damage first.',
          'If there is damage beyond normal wear, they must give you an itemised statement of what they kept and why, plus the balance, within fourteen days of you moving out. If they fail to do that they forfeit any right to the deposit.',
          'They must also tell you in writing that you may request an inspection before you move out and be present at it. After that inspection you get an itemised list of proposed repairs and cleaning — which means you have the chance to fix things yourself before the tenancy ends.',
        ],
        sources: [HPD],
      },
      {
        id: 'good-cause',
        title: 'Good Cause Eviction',
        headline: 'Since April 2024, some market-rate tenants cannot be evicted without a reason.',
        detail: [
          'Good Cause Eviction is a New York State law that took effect on 20 April 2024. It gives some tenants of unregulated — market rate — homes in New York City new protections.',
          'Owners of covered homes cannot end a tenancy without a "good cause" reason, and tenants can raise the law as a defence in Housing Court.',
          'It can also be used to challenge rent increases above a certain level where the tenant is being evicted for nonpayment.',
          'It applies to eviction cases started on or after 20 April 2024 — meaning the date the owner first filed papers in court.',
        ],
        sources: [{ label: 'HPD on Good Cause Eviction', url: HPD_GOOD_CAUSE_URL }],
      },
    ],
  },
  {
    id: 'fairness',
    title: 'Getting an apartment',
    blurb: 'What an owner may not take into account.',
    topics: [
      {
        id: 'discrimination',
        title: 'Discrimination',
        headline: 'Source of income is a protected class in New York City.',
        detail: [
          'By law an owner may not deny you housing because of race, colour, religion, nationality, gender, sexual orientation, age, marital status, disability, immigrant status, source of income, or lawful occupation.',
          'They also may not deny you housing because children live with you or will be living with you.',
          'Source of income being protected means a voucher is not a lawful reason to turn you down.',
        ],
        sources: [HPD, { label: 'Fair Housing NYC', url: FAIR_HOUSING_URL }],
      },
      {
        id: 'owner-duties',
        title: "The owner's side of the deal",
        headline: 'Safe, clean, maintained — and registered with the city every year.',
        detail: [
          'Owners must keep buildings safe, clean and well maintained, in the common areas as well as inside apartments, and must provide and maintain security measures, heat, hot and cold water, and good lighting.',
          'They must register the property with HPD annually. If the building is rent stabilized they must also register the rents annually with New York State Homes and Community Renewal.',
          'A building whose registration is missing or stale is worth noticing: the owner is already out of compliance with the one obligation that makes them reachable.',
        ],
        sources: [HPD, { label: 'The ABCs of Housing', url: HPD_ABCS_URL }],
      },
      {
        id: 'tenant-duties',
        title: 'What is asked of you',
        headline: 'Give access for required repairs, and answer legal notices.',
        detail: [
          'Tenants must comply with the law and are responsible for violations caused by willful acts, gross negligence or abuse.',
          'Unreasonably refusing the owner access to make repairs or improvements required by the Housing Maintenance Code and Multiple Dwelling Law may be grounds for eviction proceedings.',
          'You are also responsible for responding to legally required notices, including the annual lead-based paint and window guard notices.',
        ],
        sources: [HPD, { label: 'The ABCs of Housing', url: HPD_ABCS_URL }],
      },
    ],
  },
];

/** Every topic, flattened — for counting and for tests. */
export function allTopics(): readonly RightsTopic[] {
  return RIGHTS_GROUPS.flatMap((group) => group.topics);
}
